language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: clnORk8nAMIskLYEXXBaGRiQj0C4IVoFt0wmX0J9RwVT7NX9Deu4xdI02CJovQYIHK0LIZ03PBEqabKGgrtlsH8b/Xn8QtXhFYe0BOdB8iA8UUiIAKu9+0eaN4da+JJuOQr5e83JIWT46zO1fO/MCgSCnAsHGQ2dejH9Hy1CDxnc1vnimGGdJykugjVASkq5tr5xflb4xBawimLi1hUCzocFOkTMZsN33G0MtJtqJsmU81BhxwxKXFiWu6bz8KcMw+ZOOzVmRTToLue6WnWGaX+xGXGGCcD1xWFREMDd5vt9Slqb/QxEx7Twovy9GSFGHeoNgLoxej7QlBdUaqftkMQeGe33LXFlZP07pNzmyrR+1+Jdszd1AGjXA0sYbcR1qrIZVnUr+hDNVr4EgMbJKoKvnqqKqjPqw0TkKIBq38rmtdnhCzfsmB6DFa54osIrtLV4nT+gTHzGDA5j3j3yS7rIeIu5HBAuM6puzec53PSyoGvqzwDf2BYoqTeH0MCKZlphjuVaQajFQtx2Yvoh95/2ZMjM89QZWsD81FrDus7UymU5Mh5IjDQFgDtle8OMUPZXUSYVQ/iO3fmhb4FLoYGvfPwDo1Iaiz1EqZhBOPW9rSa3Fp9V1ryKRfloac1BNUdZRFFotGrghYCcXSxA3a6Oc9YTrUgyu6UlqyR6UCk=
  app: lpaproject
  on:
    repo: GiovanniAffogbolo/ProjetLPA
  run:
    - "rake db:migrate"
