language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: ZWpvmmDnTCJP2hTqbiTYBw7WEDQlLXEuLmg7Pj2mvN3CSf8Lwulc6bq/Q4l3nASf8LxvfQ4PivIrjQYY83hRl37kaHdZT6oY5Ysg+SZCL/Fel3FCpomjLptUSFgCsJkBeJdKCswGjArzZMdFjV3XXflMWhv4Hx6jsAjt8UWrRWGDPv8gfJ1L2OkKi9V2HXAbENw00KpmX7rQe9f3W4pK3rJYJw7S5FKIazWKtSu6GJe00P0N8IlJrUw2c0NswANA3dFM6ou5AuyV7FVrFmNMcYsvPl/KFDt1IH9L8Gqxq/GwrAhqcsm3cyMGbgaZNLHY2/k3Jq24lWIzF03ZESPh38dkqm6zzMTa3KvYE2pyY66OkvTlCgkLmhaQfybLkNbJWNE23xrCbHueInEijSUlMID+RIY5H8BksDIa6I80Og6KeWQZ7gYzynW55BnVVInILos2GDaVt7TQgF6xXJfh6bp/mAz48RW+rRXndIveeHdMJQim6vWEHFfuKeHRnw0Q8YSSvWVqkVPlScHMezVxjq02jJGfSsLCvTKwwU6kYg1Sw8FdYLlmuBa70LiO9ksRmkPQa7kxa7VtLGVrQyilqVT8jUp6hwTbdwzMmhRsUfR/qP4UOxdE6yIvis4t7Iaoq9XjJI9AVZ6eZXMaNjLbRP8TNt/8RMUtluddeR8MpBQ=
  app: lpaproject
  on:
    repo: GiovanniAffogbolo/ProjetLPA
  run:
  - rake db:migrate
