env:
  global:
    - CC_TEST_REPORTER_ID=bf9621b79ca889c2184951acc42441819f3796e34940f6aa61f8bbd5fb5a4cbd
language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key: d0efd909-f248-4cdd-b4fe-c2f392dd48c8
  app: lpaproject
  on:
    repo: GiovanniAffogbolo/ProjetLPA
  run:
  - rake db:migrate
  before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
