language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: BM4JE88ptmOWEdAS1hFku6zKMP7afbv74m+/gVWHcEILnYeDjMqTf+CcD2lWQts+PRSZdUDu90lnQFDg5RyK9DEEOQREigRHiYW0UrbtyAhpOGkt0V81eMH0U4jJITNL9xOZvRe0xKzlhFFXJ4k3X94w4kVBgOqxJGFZ5xW2YnYPGintWu0cLavziLWHReKU3IlM1eZg32tv72C0pAhzWV38QGcvKxd6Bj172xrNYkZRnpV1a13HBG/fQmCcrZruoit/IwMCF791+zd0abJ/bNGDIbtJsbMEthCP5M2TZU8pXG9OyQRjvVF4fWkrBMFNGMre4geyfzRDW0HXnI+kJ85x0GoZUFOGN6ZR7eKDBSkZUhBZytZWXqad+f5Yf2gl0p1RKBoXkG+72hjCP4WClJ/SlWdr6WfE3AK9omEqSraiAOoejV1cFOF4U49ykPhiRKbbOuaegbf3Pm+QAimZvWzyEkPuCWhcsQe0AYuEEHM3iWiMC3qtgHXdQgnZ+dQcVNrC029hgfoTplI9loTcQl6NWjaEtHSLLbJN3FyqGSCZpcam1UHa8RFoFy16aWqei6Cwo4DSmRV69+U2ewTpgWxSbdhmccr4UrmS3hjddJ/k3+LKyHMmNY1tdxcJNsux7NWeINlcnxclKXT+BNZDCC3LWXm9qw0wMDO6ezn22w4=
  app: ProjetLPA
  on:
    repo: GiovanniAffogbolo/ProjetLPA
