language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: gH0d7InkXr0t1tKuFzZQOJ6ZCsogRN029rlusxDh04y2lJnIkWV2U8b9JhRVJVKzvcai228mMDE2RZrKwpruZnDIIbuJ7ksOitYAScKYMcp6BjVL0Tpz1FUip7WlFJP1G+TeDp3CJg6bpBKBYvWoKRIGcYYOTMwGMILqhI7BKOyqY7Vj0CH+39dDrDlH/VAlB6TNG/bcrqAUGeH3veJx5HaRf9C0gy0JRJBz+9DjshqWRC+FxJW6ZSBAOaAKeCSw7I2U7aeuPBV9DR3rsbOr4knwMb/Zj9tyX5OcLgf8HWlJxuLx9u+p6DXiJlOz6USL+6PMdIySGFRaCIV+T5ALDedUlBsv3OIlJYfA7pobd9pPCG/LyCuAMw8s8CZa6w7owfSkFR20CoP2KSv23vWKp4lmhHoFieM5pTWdih5c5e6a5wSRWS2FJ8mD3K9wW08rx3/5xySjS4NSrM1pKjcCMXTbqHloo6y+ZJjy+0lmECBzvylOnEU9jf0XqieE4uDtqMIPfwOzozKQJ/VIaTaCwYaSyqUICTccUCjRLRY7kUjhnLhEQQsf4qGAvGTJCKFkvuDziG2umOMApNGTj/c/+3SR8J6mssu9fYcoO3H5Y21t/F0CpefoaUDQTEYTRr2iKVQ2PCwGneRzgLn9SJa6ExHPGoiy24h67h5MLfUPxEQ=
  app: lpaproject
  on:
    repo: GiovanniAffogbolo/ProjetLPA
