# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a14d6b0f5bf19060f82c530c548f5434c7b60a887f4c1ac6005c6549169c0975e83b0381fbef134c97d3db220bb2ef64eb9c421e069a1a42609a7894cb6e3a6

test:
  secret_key_base: fe9c89f1494a70b0fd1fdc1f9e29f706c2cd44a762898d2e4f8c43387f3e386666a55a9a4e7f52d47d3b6449ca92faecf15cc5c5fd63a138fe5a9aae9b86cb5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
